### ISSUE TITLE
More informative error messages when user forgets to supply starting values for all parameters in prep.formulaDynamics?

### ISSUE THREAD

**Issue by mchdfs** [mhunter1/dynr#271]
I accidentally modified the formula and forgot to add the starting values for the new parameters added. See below:

sample_formula = list(
  x ~ beta*(x-mu),
  beta ~ a0+a1*(beta-a0)
)
sample_dynamics = prep.formulaDynamics(formula = sample_formula,
                                       startval = c(mu = 1))

And it returned the following error in the dynr.cook phase:

Error in CompileCode(code, language, verbose, libLFile) : 
  Compilation ERROR, function(s)/method(s) not created!
In addition: Warning message:
In system2(paste0(R.home(component = "bin"), "/R"), args = c("CMD",  :
  running command ''/Library/Frameworks/R.framework/Resources/bin/R' CMD SHLIB file7eb83b6137a6.c 2> 'file7eb83b6137a6.c.err.txt'' had status 1

which first made me think that I had a gsl/c library issue. May we consider writing a check and putting in a more informative error message?

**Comment by mhunter1** [comment]
This is currently issue #242 

Duplicated.
